from enum import Enum


class ConnectionStatus(Enum):
    NOT_REQUESTED = "NOT_REQUESTED"
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"


class NotificationType(Enum):
    CONNECTION_REQUEST_SENT = "CONNECTION_REQUEST_SENT"
    CONNECTION_REQUEST_ACCEPTED = "CONNECTION_REQUEST_ACCEPTED"
    POST_CREATED = "POST_CREATED"
    POST_LIKE = "POST_LIKE"
    POST_COMMENT = "POST_COMMENT"
    COMMENT_LIKE = "COMMENT_LIKE"
    POST_MENTION = "POST_MENTION"


class CommentableType(Enum):
    POST = "POST"
    COMMENT = "COMMENT"


class JobType(Enum):
    FULL_TIME = "FULL_TIME"
    PART_TIME = "PART_TIME"
    CONTRACT = "CONTRACT"
    INTERN = "INTERN"
    FREELANCE = "FREELANCE"


class ApplicationStatus(Enum):
    PENDING = "PENDING"
    REVIEWED = "REVIEWED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
