from enum import Enum


class UserType(Enum):
    ADMIN = "ADMIN"
    CUSTOMER = "CUSTOMER"


class TransactionType(Enum):
    DEPOSIT = "DEPOSIT"
    WITHDRAWAL = "WITHDRAWAL"
    TRANSFER = "TRANSFER"
    BALANCE_INQUIRY = "BALANCE_INQUIRY"


class TransactionStatus(Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"


class AccountType(Enum):
    SAVINGS = "SAVINGS"
    CREDIT_CARD = "CREDIT_CARD"
    DEBIT_CARD = "DEBIT_CARD"
    LOAN = "LOAN"
    FIXED_DEPOSIT = "FIXED_DEPOSIT"


class ATMStatus(Enum):
    IDLE = "IDLE"
    CARD_INSERTED = "CARD_INSERTED"
    AUTHENTICATED = "AUTHENTICATED"
    TRANSACTION_SELECTED = "TRANSACTION_SELECTED"
    TRANSACTION_PROCESSING = "TRANSACTION_PROCESSING"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"
